---
title: "GSEA"
author: "Beverly Chigarira"
date: "1/10/2022"
output: html_document
---
```{r}
#get and set working directory
getwd()
dir =setwd("C:/Users/u6038961/Documents/R/GSEA and GO")
```

```{r}
#load libraries
library(biomaRt)
library(readr)
library(dplyr)
library(tidyr)
library(ggfortify)
library(ggplot2)
library(openxlsx)
library(clusterProfiler)
library(msigdbr) # Package that contains MSigDB gene sets in tidy format
library(org.Mm.eg.db)# Human annotation package we'll use for gene identifier conversion
library(magrittr)# We will need this so we can use the pipe: %>%


```

```{r}
#tl data
dge_df=read.csv("Results_tl_vol.csv")
head(dge_df)
nrow(dge_df)
```

```{r}
#checking packages supported
msigdbr_species()
```

```{r}
mm_hallmark_sets <- msigdbr(
  species = "Homo sapiens", # Replace with species name relevant to your data
  category = "H"
)

head(mm_hallmark_sets)
```

```{r}
#We can see what types of IDs are available to us in an annotation package with keytypes().
library(org.Hs.eg.db)
keytypes(org.Hs.eg.db)
```

```{r}
#Let’s create a data frame that shows the mapped gene symbols along with the differential expression stats for the respective Ensembl IDs.
```

```{r}
require("biomaRt")
mart <- useMart("ENSEMBL_MART_ENSEMBL")
mart <- useDataset("hsapiens_gene_ensembl", mart)

dge_mapped_df <- getBM(
  mart=mart,
  attributes=c("ensembl_gene_id", "gene_biotype", "external_gene_name"),
  filter="ensembl_gene_id",
  values=dge_df$Geneid,
  uniqueRows=TRUE)
```

```{r}
head(dge_mapped_df)
nrow(dge_mapped_df)
```


```{r}
# If an Ensembl gene identifier doesn't map to a gene symbol, drop that
  # from the data frame
names(dge_mapped_df)[1]<-paste("Geneid")
names(dge_mapped_df)[3]<-paste("symbol")

dge_mapped_df=dge_mapped_df[c("Geneid","symbol")]

dge_mapped_df

```

```{r}
dge_mapped_df
```


```{r}
dge_mapped<- merge(dge_mapped_df, dge_df, by ="Geneid")
dge_mapped

```
```{r}
#drop any columns symbol with no gene name
dge_mapped%>% dplyr::filter(!is.na(symbol)) 

```

```{r}
#Let’s check to see if we have any gene symbols that mapped to multiple Ensembl IDs.
any(duplicated(dge_mapped$symbol))
```

```{r}
#Looks like we do have duplicated gene symbols. Let’s find out which ones.

dup_gene_symbols <- dge_mapped %>%
  dplyr::filter(duplicated(symbol)) %>%
  dplyr::pull(symbol)
```

```{r}
#Now let’s take a look at the rows associated with the duplicated gene symbols.

dge_mapped %>%
  dplyr::filter(symbol %in% dup_gene_symbols) %>%
  dplyr::arrange(symbol)
```
```{r}
#In the next chunk, we are going to filter out the duplicated row using the dplyr::distinct() function This will keep the first row with the duplicated value thus keeping the row with the highest absolute value of the log2 fold change.

filtered_dge_mapped_df <- dge_mapped%>%
  # Sort so that the highest absolute values of the log2 fold change are at the
  # top
  dplyr::arrange(dplyr::desc(abs(log2FoldChange))) %>%
  # Filter out the duplicated rows using `dplyr::distinct()`
  dplyr::distinct(symbol, .keep_all = TRUE)
```


```{r}
#Let’s check to see that we removed the duplicate gene symbols and kept the rows with the higher absolute value of the log2 fold change.

any(duplicated(filtered_dge_mapped_df$symbol))
```

```{r}
#In this next chunk, we will create a named vector ranked based on the gene-level log2 fold change values.

# Let's create a named vector ranked based on the log2 fold change values
lfc_vector <- filtered_dge_mapped_df$log2FoldChange
names(lfc_vector) <- filtered_dge_mapped_df$symbol

# We need to sort the log2 fold change values in descending order here
lfc_vector <- sort(lfc_vector, decreasing = TRUE)
```

```{r}
# Look at first entries of the ranked log2 fold change vector
head(lfc_vector)
```

```{r}
#==========================================RUN GSEA================================================#



# Set the seed so our results are reproducible:
set.seed(2020)
```

```{r}
gsea_results <- GSEA(
  geneList = lfc_vector, # Ordered ranked gene list
  minGSSize = 25, # Minimum gene set size
  maxGSSize = 500, # Maximum gene set set
  pvalueCutoff = 0.05, # p-value cutoff
  eps = 0, # Boundary for calculating the p value
  seed = TRUE, # Set seed to make results reproducible
  pAdjustMethod = "BH", # Benjamini-Hochberg correction
  TERM2GENE = dplyr::select(
    mm_hallmark_sets,
    gs_name,
    gene_symbol
  )
)
```

```{r}
# We can access the results from our `gsea_results` object using `@result`
head(gsea_results@result)
```

```{r}
#Let’s convert the contents of result into a data frame that we can use for further analysis and write to a file later.

gsea_result_df <- data.frame(gsea_results@result)
```

```{r}
#+++++++++++++++++++++++++++++++++++Visualizing Results++++++++++++++++++++++++++++++++++++++++++++++++
gsea_result_df %>%
  # This returns the 3 rows with the largest NES values
  dplyr::slice_max(NES, n = 3)

```

```{r}
#The gene set HALLMARK_E2F_TARGETS has the most positive NES score.

most_positive_nes_plot <- enrichplot::gseaplot(
  gsea_results,
  geneSetID = "HALLMARK_E2F_TARGETS",
  title = "HALLMARK_E2F_TARGETS",
  color.line = "#0d76ff"
)
most_positive_nes_plot
```

```{r}
#Let’s save to PNG.

ggplot2::ggsave(file.path(dir, "TL_res_vol_positive_gsea.png"),
  plot = most_positive_nes_plot
)
```

```{r}
#Let’s look for the 3 gene sets with the most negative NES.

gsea_result_df %>%
  # Return the 3 rows with the smallest (most negative) NES values
  dplyr::slice_min(NES, n = 3)
```
```{r}
#The gene set HALLMARK_ANDROGEN_RESPONSE has the most negative NES.

most_negative_nes_plot <- enrichplot::gseaplot(
  gsea_results,
  geneSetID = "HALLMARK_ANDROGEN_RESPONSE",
  title = "HALLMARK_ANDROGEN_RESPONSE",
  color.line = "#0d76ff"
)
most_negative_nes_plot
```

```{r}
#save this plot to PNG as well.

ggplot2::ggsave(file.path(dir, "TL_res_volume_gsea_enrich_negative_plot.png"),
  plot = most_negative_nes_plot
)
```
```{r}
#Write results to file
readr::write_csv(
  gsea_result_df,
  file.path(
    dir,
    "TL_volume_gsea_results.csv"
  )
)
```





```{r}
#strip gene list from the results into a column with iensemble ids and gene symbol
heat_df =unlist(strsplit(gsea_result_df$core_enrichment,"/"))
head(heat_df)
```
```{r}
col =list(heat_df)
gsea_result_df$genes =col  
gsea_result_df$genes
p=data.frame(genes=unlist(gsea_result_df$genes))
#data.frame(y=unlist(df2))
p
```
```{r}
duplicated(p)
```
```{r}
#remove duplicates
df=distinct(p)
df
#duplicated(df) should have all false
```
```{r}
#convert geneids to ensembl
require("biomaRt")
mart <- useMart("ENSEMBL_MART_ENSEMBL")
mart <- useDataset("hsapiens_gene_ensembl", mart)
                   
df1 <- getBM(
  mart=mart,
  attributes=c("external_gene_name","ensembl_gene_id"),
  filter="external_gene_name",
  values=df$genes ,
  uniqueRows=TRUE)
```

```{r}
df1
names(df1)[1]<-paste("Gene symbol")
names(df1)[2]<-paste("Geneid")

```

```{r}
distinct(df1)
```

```{r}
write.csv(as.data.frame(df1),file ="genes_of_interest_tls.csv")
```

```{r}

```

```{r}

```

```{r}

```

```{r}

```

